Issue #39 Completed - LOGOUT IMPLEMENTATION SUCCESSFUL
G9-W2022-COMP231/OurRecipes pull request #97
Opened 2022-03-30 05:30 UTC by bhagyeshbhavsar

Issue #39 Completed - LOGOUT IMPLEMENTATION SUCCESSFUL

2022-04-02 04:10 UTC, JameeKim requested changes

2022-04-02 04:10 UTC, JameeKim commented on app/utils/auth.server.ts
> +  export const clearLoginSession = async (request: Request) => {
There is already a function defined for this at the bottom. You do not need to create another one.

2022-04-02 04:10 UTC, JameeKim commented on app/routes/logout.tsx
> +export const loader: LoaderFunction = async ({ request }) => {
Logout functionality should not be handled by the loader. See `app/routes/logout.tsx` in https://remix.run/docs/en/v1/tutorials/jokes#build-logout-action

2022-04-02 04:10 UTC, JameeKim commented on app/components/navigation.tsx
> +            <NavLink to="/logout" className="nav-link">
This should be a form that sends its data to the logout route. But it's actually out of scope for your task. It's something to be handled by #38.

2022-04-05 19:38 UTC, JameeKim requested changes
Thanks for the work! I made a couple suggestions, and you should be able to create a commit with those applied by clicking on the `Add suggestion to batch` buttons.

2022-04-05 19:38 UTC, JameeKim commented on app/components/navigation.tsx
>              <NavLink to="/profile/:id" className="nav-link">
The url is actually changed since this was written.
```suggestion
            <NavLink to="/account" className="nav-link">
```

2022-04-05 19:38 UTC, JameeKim commented on app/routes/logout.tsx
> +import { logout } from "../../app/utils/auth.server";
Since we already have something to change, let's tidy this up while we're at it.
```suggestion
import { logout } from "~/utils/auth.server";
```

2022-04-05 19:46 UTC, JameeKim approved these changes
Awesome, thanks!

2022-04-05 19:59 UTC, merged

2022-04-05 19:59 UTC, bhagyeshbhavsar commented
Estimated Time: 1.5 Hours
Actual Time: 1.5 Hours